nome= str(input('qual seu nome')).strip()
print('analisando seu nome....')
print('seu nome maiusculo é {}'.format(nome.upper()))
print('Seu nome minusculo é {}'.format(nome.lower()))
print('seu nome tem {} letras'.format(len(nome)-nome.count(' '))) 
print('seu primeiro nome tem {} letras'.format(nome.find(' ')))  